version: "2.3"

services:
  dht-node:
    image: dhtnode
    build:
      context: .
      dockerfile: dht.Dockerfile
    environment:
      CHORD_PORT: 5555
      BROADCAST_PORT: 5556
      PYTHONUNBUFFERED: 1
    volumes:
      - ./data:/app/data
    networks:
      - chord
    expose:
      - 5555
      - 5556
    deploy:
      mode: replicated
      replicas: 10

networks:
  chord:
